# Generated by Django 3.2.4 on 2021-11-15 11:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('last_name', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(related_name='users', to='myapi.Courses')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('end_at', models.DateTimeField(default=datetime.datetime(2021, 11, 22, 13, 23, 54, 300420))),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizs', to='myapi.courses')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
                ('users', models.ManyToManyField(related_name='quizs', to='myapi.User')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('point', models.IntegerField()),
                ('option1', models.CharField(max_length=150)),
                ('option2', models.CharField(max_length=150)),
                ('option3', models.CharField(max_length=150)),
                ('option4', models.CharField(max_length=150)),
                ('correct_answer', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='myapi.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='myapi.user'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('point', models.IntegerField()),
                ('user_answer', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='anwsers', to='myapi.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='anwsers', to='myapi.user')),
            ],
        ),
    ]
