# Generated by Django 3.2.4 on 2021-11-25 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20211116_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 9, 1, 44, 225789)),
        ),
    ]
