# Generated by Django 4.0.1 on 2022-01-17 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_quiz_end_at_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 9, 1, 12, 743127)),
        ),
    ]
