# Generated by Django 4.0.1 on 2022-03-04 09:05

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_alter_quiz_end_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.IntegerField(default=0)),
                ('title', models.TextField()),
                ('image', models.ImageField(default='', upload_to='')),
                ('correct_answer', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YNQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.IntegerField(default=0)),
                ('title', models.TextField()),
                ('image', models.ImageField(default='', upload_to='')),
                ('correct_answer', models.CharField(choices=[('T', 'True'), ('T', 'False')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='point',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 11, 5, 39, 507108)),
        ),
    ]
