# Generated by Django 4.0.1 on 2022-03-04 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "require_type",
                    models.CharField(
                        choices=[
                            ("POINT", "POINT"),
                            ("NUMBER_OF_QUIZS", "NUMBER_OF_QUIZS"),
                            (
                                "NUMBER_OF_CORRECT_QUESTION",
                                "NUMBER_OF_CORRECT_QUESTION",
                            ),
                            ("ACTIVE", "ACTIVE"),
                        ],
                        max_length=40,
                    ),
                ),
                ("require", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="badge",
            name="points",
        ),
        migrations.AddField(
            model_name="badge",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="badge",
            name="enable",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="badge",
            name="rules",
            field=models.ManyToManyField(related_name="badges", to="badges.Rule"),
        ),
    ]
