# Generated by Django 4.0.1 on 2022-04-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0006_rules_group_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='group_key',
            field=models.IntegerField(null=True),
        ),
    ]
