# Generated by Django 4.0.4 on 2022-05-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0007_alter_rules_group_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementlevel',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
